// Application constants

export const API_ROUTES = {
  AUTH: '/auth',
  USERS: '/users',
  TRANSACTIONS: '/transactions',
  PAYMENTS: '/payments',
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export const TRANSACTION_LIMITS = {
  MAX_TIP_AMOUNT: 500,
  MIN_TIP_AMOUNT: 0.01,
} as const;
